-- Persist raw core booking API request/response for audit and troubleshooting.

CREATE TABLE IF NOT EXISTS public.core_booking_api_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    trace_id character varying(36),
    endpoint character varying(500) NOT NULL,
    session_id character varying(36),
    request_data text,
    response_data text,
    http_status character varying(10),
    status character varying(50),
    error_message text,
    created_at timestamp(6) without time zone NOT NULL DEFAULT NOW(),
    created_time_offset character varying(32)
);

CREATE INDEX IF NOT EXISTS idx_core_booking_api_log_trace_id
    ON public.core_booking_api_log (trace_id)
    WHERE trace_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_core_booking_api_log_user_created
    ON public.core_booking_api_log (user_id, created_at DESC)
    WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_core_booking_api_log_endpoint_created
    ON public.core_booking_api_log (endpoint, created_at DESC);
