ALTER TABLE deposit_bank
    ADD COLUMN IF NOT EXISTS opening_balance numeric(19,4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_balance numeric(19,4) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS bank_ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id bigint NOT NULL REFERENCES deposit_bank(id),
    entry_type varchar(16) NOT NULL,
    category varchar(32) NOT NULL,
    entry_channel varchar(16) NOT NULL,
    amount numeric(19,4) NOT NULL,
    currency varchar(3) NOT NULL,
    balance_after numeric(19,4) NOT NULL,
    source_type varchar(32) NOT NULL,
    source_id bigint,
    reference varchar(64),
    description text,
    created_at timestamp NOT NULL DEFAULT now(),
    created_by varchar(64)
);

CREATE INDEX IF NOT EXISTS idx_bank_ledger_entries_bank_id_created_at
    ON bank_ledger_entries (bank_id, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS uq_bank_ledger_entries_source
    ON bank_ledger_entries (source_type, source_id)
    WHERE source_id IS NOT NULL;

ALTER TABLE supplier_transaction_histories
    ADD COLUMN IF NOT EXISTS deposit_bank_id bigint REFERENCES deposit_bank(id);

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'View Bank Ledger', 'view-bank-ledger', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'view-bank-ledger');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Create Bank Withdrawal', 'create-bank-withdrawal', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'create-bank-withdrawal');

INSERT INTO public.roles_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.slug = 'admin' AND r.agency_id IS NULL
  AND p.slug IN ('view-bank-ledger', 'create-bank-withdrawal')
  AND NOT EXISTS (
      SELECT 1 FROM public.roles_permissions rp
      WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
