-- Branches lookup table, supplier assignment, and permissions

CREATE TABLE IF NOT EXISTS public.branches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id bigint,
    name character varying(100) NOT NULL,
    description text,
    address character varying(255),
    phone_number character varying(15),
    is_active boolean NOT NULL DEFAULT true,
    is_deleted boolean NOT NULL DEFAULT false,
    created_by bigint NOT NULL,
    updated_by bigint,
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    update_at timestamp without time zone,
    created_time_offset character varying(32),
    updated_time_offset character varying(32)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_branches_agency_id'
    ) THEN
        ALTER TABLE public.branches
            ADD CONSTRAINT fk_branches_agency_id
                FOREIGN KEY (agency_id) REFERENCES public.users (id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_branches_agency_id ON public.branches (agency_id);
CREATE INDEX IF NOT EXISTS idx_branches_is_deleted ON public.branches (is_deleted);

ALTER TABLE public.suppliers
    ADD COLUMN IF NOT EXISTS branch_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_suppliers_branch_id'
    ) THEN
        ALTER TABLE public.suppliers
            ADD CONSTRAINT fk_suppliers_branch_id
                FOREIGN KEY (branch_id) REFERENCES public.branches (id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_suppliers_branch_id ON public.suppliers (branch_id);

-- API permissions (module API)
INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'View Branches', 'view-branch', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'view-branch');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Create Branch', 'create-branch', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'create-branch');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Update Branch', 'update-branch', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'update-branch');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Delete Branch', 'delete-branch', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'delete-branch');

-- Menu permissions (module MENU)
INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'View Branches Menu', 'view-branch-m', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'view-branch-m');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'View Branches Menu Action', 'view-branch-ma', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'view-branch-ma');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Create Branch Menu', 'create-branch-m', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'create-branch-m');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Create Branch Menu Action', 'create-branch-ma', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'create-branch-ma');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Update Branch Menu', 'update-branch-m', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'update-branch-m');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Update Branch Menu Action', 'update-branch-ma', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'update-branch-ma');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Delete Branch Menu', 'delete-branch-m', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'delete-branch-m');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Delete Branch Menu Action', 'delete-branch-ma', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'delete-branch-ma');

INSERT INTO public.roles_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.slug = 'admin' AND r.agency_id IS NULL
  AND p.slug IN (
      'view-branch',
      'create-branch',
      'update-branch',
      'delete-branch',
      'view-branch-m',
      'view-branch-ma',
      'create-branch-m',
      'create-branch-ma',
      'update-branch-m',
      'update-branch-ma',
      'delete-branch-m',
      'delete-branch-ma'
  )
  AND NOT EXISTS (
      SELECT 1 FROM public.roles_permissions rp
      WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
