CREATE TABLE IF NOT EXISTS public.activity_log (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type                 character varying(80)  NOT NULL,
    event_category             character varying(40)  NOT NULL,
    outcome                    character varying(20)  NOT NULL,

    actor_type                 character varying(20)  NOT NULL,
    actor_id                   bigint,
    actor_email                character varying(255),
    impersonated_by_admin_id   bigint,

    resource_type              character varying(50),
    resource_id                character varying(100),

    description                character varying(500),
    metadata                   text,

    ip_address                 character varying(45),
    user_agent                 character varying(500),
    trace_id                   character varying(36),
    http_method                character varying(10),
    http_path                  character varying(500),

    created_at                 timestamp(6) without time zone NOT NULL DEFAULT NOW(),
    created_time_offset        character varying(32)
);

CREATE INDEX IF NOT EXISTS idx_activity_log_created_at
    ON public.activity_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_log_actor
    ON public.activity_log (actor_type, actor_id, created_at DESC)
    WHERE actor_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_activity_log_event
    ON public.activity_log (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_log_resource
    ON public.activity_log (resource_type, resource_id)
    WHERE resource_type IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_activity_log_trace
    ON public.activity_log (trace_id)
    WHERE trace_id IS NOT NULL;
