-- Configurable outbound webhook alerts (Discord, Slack, Teams, generic JSON)

CREATE TABLE IF NOT EXISTS public.webhook_alert_configs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(150) NOT NULL,
    alert_type character varying(100) NOT NULL,
    channel character varying(50) NOT NULL,
    webhook_url text NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone
);

CREATE INDEX IF NOT EXISTS idx_webhook_alert_configs_alert_type
    ON public.webhook_alert_configs (alert_type);

CREATE INDEX IF NOT EXISTS idx_webhook_alert_configs_active
    ON public.webhook_alert_configs (is_active);

-- API permissions
INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'View Webhook Alert Configs', 'view-webhook-alert-config', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'view-webhook-alert-config');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Create Webhook Alert Config', 'create-webhook-alert-config', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'create-webhook-alert-config');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Update Webhook Alert Config', 'update-webhook-alert-config', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'update-webhook-alert-config');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Delete Webhook Alert Config', 'delete-webhook-alert-config', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'delete-webhook-alert-config');

-- Menu permissions
INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'View Webhook Alert Configs Menu', 'view-webhook-alert-config-m', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'view-webhook-alert-config-m');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'View Webhook Alert Configs Menu Action', 'view-webhook-alert-config-ma', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'view-webhook-alert-config-ma');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Create Webhook Alert Config Menu', 'create-webhook-alert-config-m', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'create-webhook-alert-config-m');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Create Webhook Alert Config Menu Action', 'create-webhook-alert-config-ma', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'create-webhook-alert-config-ma');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Update Webhook Alert Config Menu', 'update-webhook-alert-config-m', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'update-webhook-alert-config-m');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Update Webhook Alert Config Menu Action', 'update-webhook-alert-config-ma', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'update-webhook-alert-config-ma');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Delete Webhook Alert Config Menu', 'delete-webhook-alert-config-m', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'delete-webhook-alert-config-m');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Delete Webhook Alert Config Menu Action', 'delete-webhook-alert-config-ma', 'MENU', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'delete-webhook-alert-config-ma');

INSERT INTO public.roles_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.slug = 'admin' AND r.agency_id IS NULL
  AND p.slug IN (
      'view-webhook-alert-config',
      'create-webhook-alert-config',
      'update-webhook-alert-config',
      'delete-webhook-alert-config',
      'view-webhook-alert-config-m',
      'view-webhook-alert-config-ma',
      'create-webhook-alert-config-m',
      'create-webhook-alert-config-ma',
      'update-webhook-alert-config-m',
      'update-webhook-alert-config-ma',
      'delete-webhook-alert-config-m',
      'delete-webhook-alert-config-ma'
  )
  AND NOT EXISTS (
      SELECT 1 FROM public.roles_permissions rp
      WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
