-- V{n}__create_tabby_payments_table.sql

CREATE TABLE tabby_payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP NOT NULL DEFAULT now(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255) NOT NULL,
    user_id         BIGINT,
    order_id        VARCHAR(255) NOT NULL,
    payment_id      VARCHAR(255) NOT NULL,
    amount          NUMERIC(19, 2) NOT NULL,
    currency        VARCHAR(10) NOT NULL,
    status          VARCHAR(30) NOT NULL,
    checkout_url    VARCHAR(1000),
    version         BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uq_tabby_payments_order_id UNIQUE (order_id),
    CONSTRAINT uq_tabby_payments_payment_id UNIQUE (payment_id)
);

CREATE INDEX idx_tabby_payments_user_id ON tabby_payments (user_id);
CREATE INDEX idx_tabby_payments_status ON tabby_payments (status);

COMMENT ON TABLE tabby_payments IS 'Tracks Tabby payment gateway transactions linked to bookings';