INSERT INTO notification_templates (type_code, locale, title_template, message_template, default_priority, default_reference_type) VALUES
('BOOKING_CONFIRMED', 'en', 'Booking Confirmed', 'Your booking {bookingId} has been confirmed.', 'MEDIUM', 'BOOKING'),
('BOOKING_CANCELLED', 'en', 'Booking Cancelled', 'Your booking {bookingId} has been cancelled.', 'HIGH', 'BOOKING'),
('BOOKING_TICKET_ISSUED', 'en', 'Ticket Issued', 'Your ticket for booking {bookingId} has been issued.', 'MEDIUM', 'BOOKING'),
('BOOKING_PRICE_CHANGED', 'en', 'Price Changed', 'The price for booking {bookingId} has changed to {amount}.', 'HIGH', 'BOOKING'),
('PAYMENT_SUCCESS', 'en', 'Payment Successful', 'Your payment of {amount} was successful.', 'MEDIUM', 'PAYMENT'),
('PAYMENT_FAILED', 'en', 'Payment Failed', 'Your payment of {amount} failed. Please try again.', 'HIGH', 'PAYMENT'),
('WALLET_DEPOSIT_CREATED', 'en', 'Deposit Requested', 'Your deposit request of {amount} has been submitted.', 'MEDIUM', 'DEPOSIT'),
('WALLET_DEPOSIT_APPROVED', 'en', 'Deposit Approved', 'Your deposit of {amount} has been approved.', 'MEDIUM', 'DEPOSIT'),
('WALLET_DEPOSIT_CANCELLED', 'en', 'Deposit Cancelled', 'Your deposit of {amount} has been cancelled.', 'MEDIUM', 'DEPOSIT'),
('CREDIT_REQUESTED', 'en', 'Credit Requested', 'Your credit request {creditId} has been submitted.', 'MEDIUM', 'CREDIT'),
('CREDIT_APPROVED', 'en', 'Credit Approved', 'Your credit request {creditId} has been approved.', 'MEDIUM', 'CREDIT'),
('CREDIT_REJECTED', 'en', 'Credit Rejected', 'Your credit request {creditId} has been rejected.', 'MEDIUM', 'CREDIT'),
('BUSINESS_CREATED', 'en', 'Business Created', 'Business {businessName} has been created.', 'LOW', 'BUSINESS'),
('BUSINESS_APPROVED', 'en', 'Business Approved', 'Business {businessName} has been approved.', 'MEDIUM', 'BUSINESS'),
('BUSINESS_REJECTED', 'en', 'Business Rejected', 'Business {businessName} has been rejected.', 'MEDIUM', 'BUSINESS'),
('AGENCY_APPROVED', 'en', 'Agency Approved', 'Your agency application has been approved.', 'MEDIUM', 'AGENCY'),
('AGENCY_REJECTED', 'en', 'Agency Rejected', 'Your agency application has been rejected.', 'MEDIUM', 'AGENCY'),
('VISA_APPLICATION_UPDATE', 'en', 'Visa Application Update', 'Your visa application {applicationId} has an update: {status}.', 'MEDIUM', 'VISA'),
('TOUR_APPLICATION_UPDATE', 'en', 'Tour Application Update', 'Your tour application {applicationId} has an update: {status}.', 'MEDIUM', 'TOUR'),
('ACCOUNT_UPDATED', 'en', 'Account Updated', 'Your account details have been updated.', 'LOW', 'ACCOUNT'),
('ACCOUNT_VERIFIED', 'en', 'Account Verified', 'Your account has been verified.', 'MEDIUM', 'ACCOUNT'),
('ACCOUNT_WELCOME_USER', 'en', 'Welcome!', 'Welcome aboard, {userName}!', 'LOW', NULL),
('ACCOUNT_LOGIN_ALERT', 'en', 'New Login Detected', 'A new login was detected from {device} at {location}.', 'HIGH', NULL),
('PROMOTION_OFFER', 'en', 'New Offer For You', '{message}', 'LOW', 'PROMOTION'),
('SYSTEM_ALERT', 'en', 'System Alert', '{message}', 'HIGH', NULL),
('SYSTEM_GENERAL', 'en', 'Notification', '{message}', 'LOW', NULL);