-- Improve error_log query/cleanup performance and enable monthly range partitioning.

UPDATE public.error_log
SET created_at = NOW()
WHERE created_at IS NULL;

ALTER TABLE public.error_log
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_error_log_created_at_desc
    ON public.error_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_error_log_service_created
    ON public.error_log (service_name, created_at DESC);

ALTER TABLE public.error_log RENAME TO error_log_legacy;

CREATE TABLE public.error_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL DEFAULT NOW(),
    endpoint character varying(500),
    error_code character varying(100),
    error_message text NOT NULL,
    ip_address character varying(45),
    method character varying(10),
    request_data text,
    response_data text,
    service_name character varying(100) NOT NULL,
    stack_trace text,
    status_code character varying(10),
    user_agent text,
    user_id bigint,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE public.error_log_default PARTITION OF public.error_log DEFAULT;

INSERT INTO public.error_log (
    id,
    created_at,
    endpoint,
    error_code,
    error_message,
    ip_address,
    method,
    request_data,
    response_data,
    service_name,
    stack_trace,
    status_code,
    user_agent,
    user_id
)
SELECT
    id,
    created_at,
    endpoint,
    error_code,
    error_message,
    ip_address,
    method,
    request_data,
    response_data,
    service_name,
    stack_trace,
    status_code,
    user_agent,
    user_id
FROM public.error_log_legacy;

DROP TABLE public.error_log_legacy;
