-- Sales-person role, permissions, and business many-to-many relation

CREATE TABLE IF NOT EXISTS public.business_sales_persons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id bigint NOT NULL REFERENCES public.businesses(id),
    admin_user_id bigint NOT NULL REFERENCES public.admin_users(id),
    created_at timestamp(6) without time zone DEFAULT now(),
    CONSTRAINT uk_business_sales_person UNIQUE (business_id, admin_user_id)
);

CREATE INDEX IF NOT EXISTS idx_business_sales_persons_business_id
    ON public.business_sales_persons (business_id);

CREATE INDEX IF NOT EXISTS idx_business_sales_persons_admin_user_id
    ON public.business_sales_persons (admin_user_id);

-- Global sales-person role
INSERT INTO public.roles (is_active, name, slug, agency_id)
SELECT true, 'Sales Person', 'sales-person', NULL
WHERE NOT EXISTS (
    SELECT 1 FROM public.roles WHERE slug = 'sales-person' AND agency_id IS NULL
);

-- Sales-person management permissions (removed in V10; access is full-admin only)
INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Create Sales Person', 'admin-create-sales-person', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'admin-create-sales-person');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'View Sales Person', 'admin-view-sales-person', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'admin-view-sales-person');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Update Sales Person', 'admin-update-sales-person', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'admin-update-sales-person');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Delete Sales Person', 'admin-delete-sales-person', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'admin-delete-sales-person');

INSERT INTO public.permissions (is_active, name, slug, module, type)
SELECT true, 'Assign Sales Person To Business', 'assign-sales-person-to-business', 'API', 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM public.permissions WHERE slug = 'assign-sales-person-to-business');

INSERT INTO public.roles_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.slug = 'admin' AND r.agency_id IS NULL
  AND p.slug IN (
      'admin-create-sales-person',
      'admin-view-sales-person',
      'admin-update-sales-person',
      'admin-delete-sales-person',
      'assign-sales-person-to-business'
  )
  AND NOT EXISTS (
      SELECT 1 FROM public.roles_permissions rp
      WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
