package com.aerionsoft.application.enums.notification;

public enum NotificationType {
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    TICKET_ISSUED,
    PRICE_CHANGED,
    VISA_APPLICATION_UPDATE,
    TOUR_APPLICATION_UPDATE,
    ACCOUNT_UPDATE,
    SYSTEM_ALERT,
    PROMOTION,
    GENERAL,
    ACCOUNT_VERIFIED,
    WELCOME_USER,
    LOGIN_ALERT,
    TICKET_ACTION_SUBMITTED,
    TICKET_ACTION_QUOTED,
    TICKET_ACTION_REJECTED,
    TICKET_ACTION_CONFIRMED,
    TICKET_ACTION_PROCESSING,
    TICKET_ACTION_COMPLETED,
    TICKET_ACTION_FAILED
}

